{% set python_min = "3.11" %}
{% set name = "pygmt" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5921db8cd71d0da5d60afee36eaba496c953797e38b53b32583ed4ae61fab640

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools_scm >=6.2
    - toml
  run:
    - gmt >=6.4.0,<7.0
    - netcdf4
    - numpy >=1.26
    - packaging >=24.2
    - pandas >=2.1
    - python >={{ python_min }}
    - xarray >=2023.07

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygmt
  commands:
    - python -c "import pygmt; assert pygmt.__version__ != 'v0.0.0'"
    - python -c "import pygmt; pygmt.show_versions()"

about:
  home: https://www.pygmt.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python interface for the Generic Mapping Tools
  doc_url: https://www.pygmt.org/
  dev_url: https://github.com/GenericMappingTools/pygmt

extra:
  recipe-maintainers:
    - moorepants
    - seisman
    - weiji14
    - willschlitzer
