{% set name = "pygmt" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7eb1d4957b10b2281376606d7f40896da4d657988e1c93a2d1224750d3e1dbd0

build:
  number: 0
  # TODO : pygmt does not yet work with gmt on Windows, see this PR:
  # https://github.com/GenericMappingTools/pygmt/pull/313. Once that is merged,
  # the Windows builds here can likely be enabled.
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - gmt >=6.0.0,<7.0
    - netCDF4
    - numpy
    - packaging
    - pandas
    - python
    - xarray

test:
  imports:
    - pygmt
    - pygmt.tests

about:
  home: https://www.pygmt.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python interface for the Generic Mapping Tools
  doc_url: https://www.pygmt.org/
  dev_url: https://github.com/GenericMappingTools/pygmt

extra:
  recipe-maintainers:
    - moorepants
    - weiji14
