{% set name = "pygmt" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9033cd040ed4710e61397fb4c03a0577b8aa2fc9e3618437c2a7b3dfa97cf4a4

build:
  noarch: python
  number: 1
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - gmt >=6.1.1,<7.0
    - netCDF4
    - numpy
    - packaging
    - pandas
    - python >=3.6
    - xarray

test:
  imports:
    - pygmt
    - pygmt.tests
  commands:
    - python -c "import pygmt; assert pygmt.__version__ != 'v0.0.0'"
    - python -c "import pygmt; pygmt.show_versions()"

about:
  home: https://www.pygmt.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python interface for the Generic Mapping Tools
  doc_url: https://www.pygmt.org/
  dev_url: https://github.com/GenericMappingTools/pygmt

extra:
  recipe-maintainers:
    - moorepants
    - seisman
    - weiji14
    - willschlitzer
