{% set name = "pygmt" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d95c2825c3bc368b17e6c5c308179a05f4539aaf2fef4379b6c7bb6125882113

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - gmt >=6.0.0,<7.0
    - netCDF4
    - numpy
    - packaging
    - pandas
    - python
    - xarray

test:
  # TODO: pygmt does not yet work with gmt conda package on Windows, see this PR:
  # https://github.com/GenericMappingTools/pygmt/pull/313. Once that is merged,
  # remove the [not win] tag to enable tests on Windows
  imports:
    - pygmt
    - pygmt.tests  # [not win]

about:
  home: https://www.pygmt.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Python interface for the Generic Mapping Tools'
  doc_url: https://www.pygmt.org/
  dev_url: https://github.com/GenericMappingTools/pygmt

extra:
  recipe-maintainers:
    - moorepants
    - weiji14
