{% set name = "pygmt" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ec644c4ee45b5fddc84d7dfe88a449ba230ed75224396321696c00b4357f8f4

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=64
    - setuptools_scm >=6.2
    - toml
  run:
    - gmt >=6.3.0,<7.0
    - netcdf4
    - numpy >=1.23
    - packaging
    - pandas >=1.5
    - python >=3.10
    - xarray >=2022.06

test:
  imports:
    - pygmt
  commands:
    - python -c "import pygmt; assert pygmt.__version__ != 'v0.0.0'"
    - python -c "import pygmt; pygmt.show_versions()"

about:
  home: https://www.pygmt.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python interface for the Generic Mapping Tools
  doc_url: https://www.pygmt.org/
  dev_url: https://github.com/GenericMappingTools/pygmt

extra:
  recipe-maintainers:
    - moorepants
    - seisman
    - weiji14
    - willschlitzer
