schema_version: 1

context:
  python_min: 3.11
  name: pygmt
  version: 0.17.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 06d7581bc35641db318c418aba02163bc519ba267a5a60b5cc419eee40390503

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools_scm >=6.2
    - toml
  run:
    - gmt >=6.5.0,<7.0
    - numpy >=1.26
    - packaging >=24.2
    - pandas >=2.2
    - python >=${{ python_min }}
    - xarray >=2023.10

tests:
  - python:
      imports:
        - pygmt
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python -c "import pygmt; assert pygmt.__version__ != 'v0.0.0'"
      - python -c "import pygmt; pygmt.show_versions()"

about:
  homepage: https://www.pygmt.org
  documentation: https://www.pygmt.org
  repository: https://github.com/GenericMappingTools/pygmt
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Python interface for the Generic Mapping Tools

extra:
  recipe-maintainers:
    - moorepants
    - seisman
    - weiji14
    - willschlitzer
